updated schema for dataset type
Ensembl/ensembl-metadata-admin pull request #30
Opened 2024-02-06 16:08 UTC by dpopleton

2024-02-06 16:20 UTC, marcoooo requested changes

2024-02-06 16:20 UTC, marcoooo commented on src/ensembl/production/metadata/admin/models.py
> +from django.contrib.postgres.fields import JSONField
I am quite sure we don't want to import PostGres Fields.

2024-02-21 14:10 UTC, marcoooo approved these changes

2024-02-22 08:06 UTC, vinay-ebi approved these changes

2024-02-28 16:50 UTC, merged